---
# This playbook deploys the whole application stack in this site.  

- hosts: controller
  roles:
  - mysql


- hosts: controller1
  roles:
  - rabbitmq

- hosts: controller2
  roles:
  - rabbitmq

- hosts: controller3
  roles:
  - rabbitmq
