---
# This playbook deploys the whole application stack in this site.  

- hosts: controller
  roles:
  - common
  - mysql

- hosts: controller
  tasks:
  - name: Stop rabbitmq-server Service
    service: name=rabbitmq-server state=stopped enabled=true

- hosts: controller1
  roles:
  - rabbitmqcluster

- hosts: controller2
  roles:
  - rabbitmqcluster

- hosts: controller3
  roles:
  - rabbitmqcluster
