---
# This role contains common plays that will run on all nodes.
- name: upgrade all packages
  yum: name=* state=latest

- name: restart machine
  command: shutdown -r now "Ansible updates triggered"
  async: 0
  poll: 0
  ignore_errors: true

- name: waiting for server to come back
  local_action: wait_for host={{ inventory_hostname }}
                state=started
