---
# TODO: This role can be done in cobbler!!
# This role contains common plays that will run on all nodes.

- name: Remove all the repo
  shell: rm -rf /etc/yum.repos.d/*.repo

# TODO: use template to support different repo address
- name: Create the ocp repository
  copy: src=etc/yum.repos.d/ocp.repo dest=/etc/yum.repos.d/ocp.repo

- name: Clean up repo cache
  shell: yum clean all 

# Disable Firewalld
- name: Disable Firewalld
  service: name=firewalld state=stopped enabled=false

# Disable SELinux
- name: Disable SELinux by command
  shell: /usr/sbin/setenforce 0
  ignore_errors: True

- name: Disable SELinux in config
  selinux: state=disabled

# NTP
- name: Install ntp 
  yum: name=ntp state=present

- name: Configure ntp file
  template: src=etc/ntp.conf.j2 dest=/etc/ntp.conf
  notify: restart ntp

- name: Start the ntp service
  service: name=ntpd state=started enabled=true

# Hosts
- name: Build hosts file
  lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line="{{ hostvars[item].ansible_default_ipv4.address }} {{ item }}.{{ domainname }} {{ item }}" state=present
  when: hostvars[item].ansible_default_ipv4.address is defined
  with_items: groups['all']

# Hostname
- name: Config hostname
  hostname: name={{ inventory_hostname }}.{{ domainname }}

# DNS
- name: Confiture dns server
  template: src=etc/resolv.conf.j2 dest=/etc/resolv.conf

# Install common packages
- name: Install some tools
  yum: name={{ item }} state=present
  with_items:
    - net-tools
    - vim
    - htop
    - psmisc
    - MySQL-python
    - kexec-tools
    - wget
    - lrzsz
